- name: Ensure required dependencies
  apt:
    name: software-properties-common
    state: present

- name: Ensure HashiCorp GPG key
  apt_key:
    url: "{{ terraform_hashicorp_GPG_key }}"
    state: present

- name: Ensure HashiCorp APT repository
  apt_repository:
    repo: "{{ terraform_hashicorp_repository }}"
    state: present

- name: Update the apt package index
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install Terraform
  apt:
    name: terraform
    state: present

- name: Verify Terraform installation
  command: terraform version
  register: terraform_version

- name: Display Terraform version
  debug:
    msg: "Terraform version installed: {{ terraform_version.stdout }}"
  when: not ansible_check_mode
