# Installed Packages Management
base_packages:
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - dnsutils
  - htop
  - iotop
  - netcat
  - software-properties-common
  - python3
  - python3-pip
  - sl
  - vim

# ~/.bashrc config
base_bashrc_block: |
    # Vim aliases
    alias svim='sudo -E vim'
    alias svb='sudo -E vim ~/.bashrc'

    # Docker aliases
    alias docker-rm-all='docker rm -f $(docker ps -aq)'
    alias docker-prune-all='docker container prune -f && docker image prune -f'

    # Kubectl aliases
    alias kc='kubectl'
    alias kcc='kubectl config'
