# General Variable
ancible_managed: 'WARNING: This file is managed by Ansible. Any changes will be overwritten.'

# Installed Packages Management
base_packages:
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - dnsutils
  - htop
  - iotop
  - netcat
  - software-properties-common
  - python3
  - python3-pip
  - sl
  - vim

# Shell config
base_shell: '.bashrc'
base_shell_block: |
    # Vim aliases
    alias svim='sudo -E vim'

    # Docker aliases
    alias docker-rm-all='docker rm -f $(docker ps -aq)'
    alias docker-prune-all='docker container prune -f && docker image prune -f'

    # Kubectl aliases
    alias kc='kubectl'
    alias kcc='kubectl config'

    # Terraform alias
    alias tf='terraform'

    # Show custom .gitignore
    alias show-gitignore='echo -e "#\n# Alex default .gitignore, any manual change will be overwritten.\n#\n
    # General untracked
    __pycache__/
    backup/
    *venv*
    \n# Environment variable files
    .env
    .env.*
    \n# Log files
    logs/
    *.log
    \n# Sensitive data
    *secret*
    *vault*
    \n# Output files
    output/
    \n# IDEs config files
    .vscode/
    .idea/
    "'

    # Show custom .dockerignore
    alias show-dockerignore='echo -e "#\n# Alex default .dockerignore, any manual change will be overwritten.\n#\n
    # General untracked
    __pycache__/
    .gitignore
    backup/
    *Dockerfile*
    docker-compose*
    README*
    old/
    unused/
    *venv*
    \n# Environment variable files
    .env
    .env.*
    \n# Log files
    logs/
    *.log
    \n# Sensitive data
    *secret*
    *vault*
    "'

    # SSH config --> ~/.ssh/config

    # Git aliases --> Configured in ~/.gitconfig

# Gitconfig
base_gitconfig_email: ''
base_gitconfig_username: ''
