# General Variable
base_ansible_managed: "WARNING: This file is managed by Ansible. Any changes will be overwritten."

# Ensure Packages Installed
base_packages:
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - dnsutils
  - htop
  - iotop
  - mysql-client
  - netcat
  - nmap
  - software-properties-common
  - python3
  - python3-pip
  - sl
  - tmux
  - vim

# Shell config
base_shell: ".zshrc" # .zshrc / .bashrc
base_shell_block: |
    # Ignore duplicate in history
    setopt HIST_IGNORE_DUPS

    # Vim aliases
    alias svim='sudo -E vim'

    # Docker aliases
    alias docker-rm-all='docker rm -f $(docker ps -aq)'
    alias docker-prune-all='docker container prune -f && docker image prune -f'

    # Kubectl aliases
    alias kc='kubectl'
    alias kcc='kubectl config'

    # Terraform alias
    alias tf='terraform'

    # Show custom .gitignore
    alias show-gitignore='echo -e "#\n# Alex default .gitignore, any manual change will be overwritten.\n#\n
    # General untracked
    __pycache__/
    backup/
    *venv*
    \n# Environment variable files
    .env
    .env.*
    \n# Log files
    logs/
    *.log
    \n# Sensitive data
    *secret*
    *password*
    \n# Output files
    output/
    \n# IDEs config files
    .vscode/
    .idea/
    "'

    # Show custom .dockerignore
    alias show-dockerignore='echo -e "#\n# Alex default .dockerignore, any manual change will be overwritten.\n#\n
    # General untracked
    __pycache__/
    .gitignore
    backup/
    *Dockerfile*
    docker-compose*
    README*
    old/
    unused/
    *venv*
    \n# Environment variable files
    .env
    .env.*
    \n# Log files
    logs/
    *.log
    \n# Sensitive data
    *secret*
    *password*
    "'

    # SSH config --> ~/.ssh/config

    # Git aliases --> Configured in ~/.gitconfig

# Gitconfig
base_gitconfig_email: ""
base_gitconfig_username: ""

# Tmux
base_tmux_key: "a"

# Docker Management
base_docker_enabled: false
base_docker_gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
base_docker_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

# Terraform Management
base_terraform_enabled: false
base_terraform_hashicorp_gpg_key: "https://apt.releases.hashicorp.com/gpg"
base_terraform_hashicorp_repository: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
