- hosts: localhost
  become: yes
  # vars:
  vars_files:
    - ../general_vars.yml
    - ../vault.yml
  # tasks:
  #   - name: Debug test_var
  #     debug:
  #       var: ansible_managed
  roles:
    - "roles/base"
