- hosts: localhost
  become: yes
  
  vars:
    base_shell: '.zshrc'
    base_gitconfig_email: 'andreasscorelli@gmail.com'
    base_gitconfig_username: 'titocampis'
  
  vars_files:
    - ../../general_vars.yaml
    - ../../vault.yaml
  
  # tasks:
  #   - name: Debug test_var
  #     debug:
  #       var: ansible_managed
  
  roles:
    - "roles/base"
