- hosts: localhost
  become: yes
  
  vars:
    docker_enabled: true
    terraform_enabled: true
  
  vars_files:
    - ../../general_vars.yaml
    - ../../vault.yaml
  
  # tasks:
  #   - name: Debug test_var
  #     debug:
  #       var: test_var
  
  roles:
    - "roles/config-services"
