- name: Ensure base packages installed
  import_tasks: base_packages.yml
  tags:
    - base
    - base-packages

- name: Bashrc useful configuration
  import_tasks: bashrc_config.yml
  tags:
    - base
    - base-bashrc-config

- name: Ensure vim configuration
  import_tasks: vim_config.yml
  tags:
    - base
    - base-vim-config
