# Beta playbook
# - name: Install Zsh
#   apt:
#     name: zsh
#     state: present

# - name: Change default shell to Zsh
#   user:
#     name: "{{ ansible_user }}"
#     shell: /bin/zsh

# - name: Download and install Oh My Zsh
#   shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#   args:
#     executable: /bin/bash

# - name: Ensure .zshrc is owned by the user
#   file:
#     path: /home/{{ ansible_user }}/.zshrc
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: '0644'
#   when: not ansible_check_mode

- name: Include useful aliases on ~/.zshrc
  blockinfile:
    path: "/home/{{ ansible_user }}/.zshrc"
    block: "{{ base_bashrc_block }}"
    state: present
